version: 2
jobs:
  base:
    docker:
      - image: docker:stable-git
    environment:
      - PACKER_VERSION: "1.2.4"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install system dependencies
          command: |
            apk add --no-progress --no-cache ansible bash openssh curl unzip
            apk -vv info|sort
      - run:
          name: Install Packer
          command: |
            curl -L -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
            unzip packer.zip
            rm packer.zip
            mv packer /usr/local/bin
            packer version
      - run:
          name: Build base
          command: |
            ./scripts/build.sh base
          no_output_timeout: 15m

  'checkout-code':
    docker:
      - image: dhutton/immute:0.0
    working_directory: ~/core/repo
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/core/repo

  'bundle-dependencies':
    docker:
      - image: dhutton/immute:0.0
    working_directory: ~/core/repo
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - bundle-deployment-{{ checksum "Gemfile.lock" }}
      - run: bundle install --deployment --path vendor/bundle
      - save_cache:
          key: bundle-deployment-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/core/repo/vendor/deployment

  test:
    docker:
      - image: dhutton/immute:0.0
    working_directory: ~/core/repo
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - bundle-deployment-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run:
          name: Fake test command
          command: echo 'Testing!'

  lint:
    docker:
      - image: dhutton/immute:0.0
    working_directory: ~/core/repo
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - bundle-deployment-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run:
          name: Fake lint command
          command: echo 'Linting!'

  package:
    docker:
      - image: dhutton/immute:0.0
    working_directory: ~/core/repo
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - bundle-deployment-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run:
          name: Fake package command
          command: echo 'Packaging! Copy the deployment folder into the release artefact'

workflows:
  version: 2
  build-base-artefact:
    jobs:
      - base:
          filters:
            branches:
              only: 'release/base'

  build-test-package:
    jobs:
      - checkout-code:
          filters:
            branches:
              ignore: 'release/base'
      - bundle-dependencies:
          requires:
            - checkout-code
          filters:
            branches:
              ignore: 'release/base'
      - lint:
          requires:
            - bundle-dependencies
          filters:
            branches:
              ignore: 'release/base'
      - test:
          requires:
            - bundle-dependencies
          filters:
            branches:
              ignore: 'release/base'
      - package:
          requires:
            - lint
            - test
          filters:
            branches:
              ignore: 'release/base'