---
# Gem system dependencies
- name: Update repositories cache and install pg gem dependencies
  apt:
    name: libpq-dev
    update_cache: yes
  tags:
    - ruby

- name: Update repositories cache and install sqlite3 gem dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - sqlite3
    - libsqlite3-dev
  tags:
    - ruby

# Output the version of dependencies, facilitates debugging long after the build runs
- command: bundle --version
  register: bundle
  tags:
    - ruby
- name: Output bundle version
  debug:
    var: bundle.stdout_lines
  tags:
    - ruby