---
# Whether this role should install Bundler.
ruby_install_bundler: True

# A list of Ruby gems to install.
ruby_install_gems: []

# The user account under which Ruby gems will be installed.
ruby_install_gems_user: "{{ ruby_user }}"

ruby_install_from_source: True
ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.gz
ruby_version: 2.3.1